# Customer variant-specific value mappings
# Inherits object-level mappings and adds more

# Extended salutation mappings
ANRED:
  "Mr.": "0001"
  "Mrs.": "0002"
  "Ms.": "0002"
  "Dr.": "0003"
  "Prof.": "0004"
  "Company": "0005"

# Industry sector mappings
BRSCH:
  "TECHNOLOGY": "0001"
  "MANUFACTURING": "0002"
  "SERVICES": "0003"
  "RETAIL": "0004"
  "FINANCE": "0005"

# Extended country mappings (adds to object-level)
LAND1:
  "Spain": "ES"
  "Italy": "IT"
  "Austria": "AT"
  "Switzerland": "CH"