# Transform MYD Minimal Configuration
# This file contains default configuration parameters that can be overridden via CLI arguments

# Default object and variant (optional - can be overridden by CLI)
# object: "m140"       # Uncomment and set default object name
# variant: "bnka"      # Uncomment and set default variant name

# Fuzzy matching configuration
fuzzy_threshold: 0.6        # Fuzzy matching threshold (0.0-1.0)
max_suggestions: 3          # Maximum number of fuzzy match suggestions  
disable_fuzzy: false        # Whether to disable fuzzy matching

# Directory configuration
input_dir: "data/02_fields" # Input directory for Excel files
output_dir: "output"        # Output directory for generated YAML files

# Advanced mapping configuration for direct source file processing
mapping:
  from_sources: true        # Enable direct mapping from source files

  source_headers:
    path: data/02_fields/BNKA_headers.xlsx
    sheet: Sheet1
    header_row: 1
    ignore_data_below: true

  target_xml:
    path: data/02_fields/Source data for Bank.xml
    worksheet_name: "Field List"
    header_match:
      sheet_name: "Sheet Name"
      group_name: "Group Name"
      description: "Field Description"
      importance: "Importance"
      type: "Type"
      length: "Length"
      decimal: "Decimal"
      sap_table: "SAP Structure"
      sap_field: "SAP Field"
    normalization:
      strip_table_prefix: "S_"
      uppercase_table_field: true
    output_naming:
      transformer_id_template: "{sap_table}#{sap_field}"
      internal_id_template: "{internal_table}.{sap_field}"

matching:
  target_label_priority:
    - description
    - sap_field
    - group_name