# Overview of all objects and their tables

Objects:
- object: m140
  tables:
  - bnka

# F100 - Internal orders
# F110 - Opening Balances
# F120 - GL Account Balance
# F130 - Open Accounts Receivable
# F140 - Open Accounts Payable
# F150 - Assets
# F160 - Fixed Assets
# F170 - Credit accounts
# F180 - Persons (PA30)
# M100 - GL Accounts
# M120 - Profit Centers
# M130 - Cost Centers
# M140 - Banks
# M150 - Material
# M151 - Material - Extend Sales
# M152 - Material - Extend Purchasing
# M153 - Material - Extend MRP
# M154 - Material - Extend Accounting
# M155 - Material - Extend WM Exe
# M160 - EWM artikel
# M170 - Material Extensions
# M180 - MRP Area
# M190 - BOM
# M200 - Long texts
# M201 - Long text purchasing
# M202 - Long text SD
# M203 - Long text material
# M210 - Vendors - Generic
# M211 - Vendors - Extend Finance c.code
# M212 - Vendors - Extend Supplier p.org
# M213 - Vendors - Extend Carrier p.org
# M220 - Vendor Extensions
# M230 - Customers - Generic
# M231 - Customers - Extend Finance c.code
# M232 - Customers - Extend Sold-to s.org
# M233 - Customers - Extend Ship-to s.org
# M234 - Customers - Extend Prospects s.org
# M240 - Customer extensions
# M260 - Source List
# M270 - Purchasing info records
# M280 - Sales info records
# M290 - Pricing conditions purchasing
# M300 - Pricing conditions sales
# M320 - Work Centers
# M330 - Control Cycles
# M340 - Routing
# M350 - Production versions
# M390 - EWM Verpakkingspecificatie
# M400 - Locations
# M410 - Routes
# M420 - Calculation Agreements
# M430 - Calculation Rates (calculation sheet)
# M440 - License Plates
# M450 - Characteristics
# M451 - Classes
# M460 - Configuration Profile for Config Materials
# T110 - Open Purchasing Order items
# T120 - Sales Contracts
# T130 - Open Sales Order items
# T140 - Production Orders
# T150 - Stock Balance
# T151 - EWM Stock Balance